version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 9092:9092
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    ports:
      - 3000:3000
  ventas:
    build:
      context: ./ventas/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 5000:3000
  coordenadas:
    build:
      context: ./coordenadas/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 5001:3000
  stock:
    build:
      context: ./stock/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - ventas
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 5002:3000
  nmiembros:
    build:
      context: ./Nmiembros/
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 5003:3000  